# Generated by Django 5.0.3 on 2024-03-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_orderproduct_item_remove_orderproduct_ordered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
