# Generated by Django 5.0.3 on 2024-03-26 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_order_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='products_new',
            new_name='products',
        ),
    ]
