# Generated by Django 5.0.3 on 2024-03-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_cart_completed_remove_cart_date_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='placed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='time_paid',
            new_name='time_placed',
        ),
    ]
