# Generated by Django 5.0.3 on 2024-03-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_session_key_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_key',
        ),
        migrations.AddField(
            model_name='cart',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
