# Generated by Django 5.0.3 on 2024-03-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='order',
            new_name='cart',
        ),
    ]
